### ISSUE TITLE
If the directory is not in `project--list`, `beframe-infer-frame-name` will stop inferring the frame name.

### ISSUE THREAD

**Issue by kilesduli** [protesilaos/beframe#5]
On line 627, `when-let` will stop when `dir` not in `project--list`, it just return nil without evaluating the remaining code.
So the default rename function won't work.
https://github.com/protesilaos/beframe/blob/c3f4583b0767e7f8c38c83ed29af40af8ba3bdfa/beframe.el#L619-L640

**Comment by protesilaos** [comment]
> From: duli ***@***.***>
> Date: Fri, 24 May 2024 05:35:22 -0700
>
> On line 627, `when-let` will stop when `dir` not in `project--list`, it just return nil without evaluating the remaining code.
> So the default rename function won't work.
> https://github.com/protesilaos/beframe/blob/c3f4583b0767e7f8c38c83ed29af40af8ba3bdfa/beframe.el#L619-L640

Sorry for the late response! I did not see this notification in time.

Does this fix the issue?

    (defun beframe-infer-frame-name (frame name)
      "Infer a suitable name for FRAME with given NAME.
    See `beframe-rename-frame'."
      (when-let (((frame-list))
                 (buffer (car (frame-parameter frame 'buffer-list)))
                 (file-name (when (bufferp buffer) (buffer-file-name buffer)))
                 (buf-name (buffer-name buffer))
                 (dir (with-current-buffer buffer (or (vc-root-dir) default-directory))))
        (let ((projectp (and (bound-and-true-p project--list)
                             (listp project--list)
                             (member (list dir) project--list))))
          (cond
           ((and name (stringp name))
            name)
           ((and projectp buf-name)
            (format "%s" (file-name-nondirectory (directory-file-name dir))))
           ((and (not (minibufferp)) file-name)
            (format "%s %s" buf-name dir))
           ((not (minibufferp))
            buf-name)
           (t
            dir)))))

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by kilesduli** [comment]
> Sorry for the late response! I did not see this notification in time. 

It's no big deal.

> Does this fix the issue?
> 
>     (defun beframe-infer-frame-name (frame name)
>       "Infer a suitable name for FRAME with given NAME.
>     See `beframe-rename-frame'."
>       (when-let (((frame-list))
>                  (buffer (car (frame-parameter frame 'buffer-list)))
>                  (file-name (when (bufferp buffer) (buffer-file-name buffer)))
>                  (buf-name (buffer-name buffer))
>                  (dir (with-current-buffer buffer (or (vc-root-dir) default-directory))))
>         (let ((projectp (and (bound-and-true-p project--list)
>                              (listp project--list)
>                              (member (list dir) project--list))))
>           (cond
>            ((and name (stringp name))
>             name)
>            ((and projectp buf-name)
>             (format "%s" (file-name-nondirectory (directory-file-name dir))))
>            ((and (not (minibufferp)) file-name)
>             (format "%s %s" buf-name dir))
>            ((not (minibufferp))
>             buf-name)
>            (t
>             dir)))))

Yes, but is there any special reason for using when-let? I thought just rewrite when-let to (when (frame-list) (let* ...) (cond ...)) seems much better. 

And I found another edge case.
Info buffer without file-name, so `M-x beframe-rename-function` won't work too. `buffer-file-name` return nil then when-let stop again.

**Comment by protesilaos** [comment]
> From: duli ***@***.***>
> Date: Sat, 27 Jul 2024 06:16:35 -0700

> [... 30 lines elided]

> Yes, but is there any special reason for using when-let? I thought
> just rewrite when-let to (when (frame-list) (let* ...) (cond ...))
> seems much better.

You are right! I am pushing this change.

> And I found another edge case.
> Info buffer without file-name, so `C-x 5 5 C-h i M-x
> beframe-rename-function` won't work too.

Strange... This seems to work on my end. Note though that I made the
change mentioned above. So maybe you got this with the previous code.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by kilesduli** [comment]
> Strange... This seems to work on my end. Note though that I made the
> change mentioned above. So maybe you got this with the previous code.

**Comment by kilesduli** [comment]
> Strange... This seems to work on my end. Note though that I made the
> change mentioned above. So maybe you got this with the previous code.

Perhaps it is the variable `frame-title-format` that caused `beframe-infer-frame-name` to seem to work properly. At least for me, adding the global parameter `C-u` then calling beframe-infer-frame-name to try renaming does not work.

Since the issue has been resolved, I am closing this issue. Thank you for your fix.
