### ISSUE TITLE
Can't make beframe-functions-in-frames to work

### ISSUE THREAD

**Issue by mcartaud** [protesilaos/beframe#9]
Hello,

First of all thanks a lot for this packages (and all the others as well as all your work on explaining emacs).

I have an issue with the `beframe-function-in-frames` function : I thought it would create a new frame when calling the functions we specified, but I can't make it work.
For instance if I use `(setq beframe-functions-in-frames '(project-prompt-project-dir))`, it should have the same behaviour than the `project-other-frame-command` (C-x 5 p) each time I have to select a project in the project list. Is this correct?

If yes, I can't get it to work, maybe I set the value incorrectly? I'm quite in the early steps of my elisp learning 
If no, can you explain the expected behaviour?

Many thanks

**Comment by mcartaud** [comment]
I managed to fix my issue. 
I had to disable/re-enable beframe for it to work. Solution was to move the `(setq beframe-functions-in-frames '(project-prompt-project-dir))` in the `:init` instead of in the `:config` (I use use-package).

**Comment by protesilaos** [comment]
> From: Mathieu Cartaud ***@***.***>
> Date: Thu, 29 Aug 2024 13:30:56 -0700
>
> I managed to fix my issue. 

Very well! Sorry for not responding to this in time.

> I had to disable/re-enable beframe for it to work. Solution was to
> remove the `(setq beframe-functions-in-frames
> '(project-prompt-project-dir))` in the `:init` instead of in the
> `:config` (I use use-package)

Oh, I see. Here is my beframe setup for reference:

    (use-package beframe
      :ensure t
      :hook (after-init . beframe-mode)
      :config
      (setq beframe-functions-in-frames '(project-prompt-project-dir))

      ;; I use this instead of :bind because I am binding a keymap and the
      ;; way `use-package' does it is by wrapping a lambda around it that
      ;; then breaks `describe-key' for those keys.
      (prot-emacs-keybind global-map
        ;; Override the `set-fill-column' that I have no use for.
        "C-x f" #'other-frame-prefix
        ;; Bind Beframe commands to a prefix key. Notice the -map as I am
        ;; binding keymap here, not a command.
        "C-c b" #'beframe-prefix-map
        ;; Replace the generic `buffer-menu'.  With a prefix argument, this
        ;; commands prompts for a frame.  Call the `buffer-menu' via M-x if
        ;; you absolutely need the global list of buffers.
        "C-x C-b" #'beframe-buffer-menu
        ;; Not specific to Beframe, but since it renames frames (by means
        ;; of `beframe-mode') it is appropriate to have this here:
        "C-x B" #'select-frame-by-name))

The 'prot-emacs-keybind' basically dones 'define-key' the 'global-map'
for those key bindings/commands you see there.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by mcartaud** [comment]
Thanks for your answer. 
The fact that you define `beframe-functions-in-frames` in the `:config` section and you `after-init` hook make me think. The real issue for me was because I was setting the `beframe-functions-in-frames` in :config while I activated the mode in :init, leading to the property not used by beframe.

After moving everything in the config section, it works flawlessly. Thanks again and sorry for the noise :)
